ADD: support multilingual & add draft of English documents / strings (#8)
cloudbandwagon/cloudbandwagon.github.io pull request #10
Opened 2023-04-01 09:40 UTC by 9bow

- 다국어 지원 기능을 추가하였습니다.
  - [polyglot 플러그인](https://github.com/untra/polyglot)을 사용했습니다.
- 영어 문서 및 문자열들을 추가하였습니다.
  - 공통 파일(`_includes/` 하위 파일)에 속한 문자열들은 `_data/[lang]/translations.yml` 파일에 정의되어 있습니다.
  - 페이지 문서(`filename.md`)는 언어별 문서(`filename.lang.md`)를 만들어 관리합니다.
    - 이 때, 각 페이지 상단에 `lang: {ko, en}`와 같은 식으로 현재 페이지가 지원하는 언어 정보를 추가해야 합니다.
    - 예. `index.md` : 한국어, `index.en.md` : 영어
- 페이지 하단에 언어별 이동 메뉴를 추가하였습니다.
  - 심각한 디자인에 대한 문제가 있어, 변경이 필요합니다;;

2023-04-01 09:43 UTC, ppiyakk2 approved these changes

2023-04-01 09:43 UTC, 9bow commented
한국어 버전 (현재 사이트)
![Uploading image.png…]()

2023-04-01 09:43 UTC, 9bow commented
영어 버전 (추가한 것)
![image](https://user-images.githubusercontent.com/9343724/229278665-65782286-96ad-42cb-bab6-53f069f65c14.png)

2023-04-01 13:02 UTC, justinyoo requested changes
몇군데 코멘트 남겨뒀습니다!

2023-04-01 13:02 UTC, justinyoo commented on _config.yml
>  ext_links:
혹시 이 부분이 예전 값으로 돌아간 듯 싶은데... 확인해 보시겠쎄요?

2023-04-01 13:02 UTC, justinyoo commented on _members/hyekyung-hwang.ko.md
`order` 위에 `lang: ko` 들어가야 하나요?

2023-04-01 13:02 UTC, justinyoo commented on _members/junghwan-park.en.md
> +order: 6
`order` 위에 `lang: en` 들어가야 하나요?

2023-04-01 13:02 UTC, justinyoo commented on _members/junghwan-park.ko.md
`order` 위에 `lang: ko` 들어가야 하나요?

2023-04-01 13:02 UTC, justinyoo commented on _members/justin-yoo.en.md
> +order: 1
`order` 위에 `lang: en` 들어가야 하나요?

2023-04-01 13:02 UTC, justinyoo commented on _members/justin-yoo.ko.md
`order` 위에 `lang: ko` 들어가야 하나요?

2023-04-01 13:02 UTC, justinyoo commented on _members/olivia-choi.en.md
> +order: 5
`order` 위에 `lang: en` 들어가야 하나요?

2023-04-01 13:02 UTC, justinyoo commented on _members/olivia-choi.ko.md
`order` 위에 `lang: ko` 들어가야 하나요?

2023-04-01 13:02 UTC, justinyoo commented on _members/seongsoo-cho.en.md
> +order: 2
`order` 위에 `lang: en` 들어가야 하나요?

2023-04-01 13:02 UTC, justinyoo commented on _members/seongsoo-cho.ko.md
`order` 위에 `lang: ko` 들어가야 하나요?

2023-04-02 03:33 UTC, 9bow commented on _config.yml
>  ext_links:
네, 한글과 영문으로 각각 나누어서 `_data/en/translations.yml`과 `_data/ko/translations.yml`에 적어두긴 하였습니다. 
https://github.com/cloudbandwagon/cloudbandwagon.github.io/pull/10/files#diff-cd90e6bdced82a3bf6a44ab35e86805d8a90a7fff7273508fac6ef17e37217a4
https://github.com/cloudbandwagon/cloudbandwagon.github.io/pull/10/files#diff-65c4291227308f114ed19b3ddb63b527077f9e381df22aec5c2fd874f660962b

2023-04-02 03:35 UTC, 9bow commented on _config.yml
>  ext_links:
아, 근데 지금 다시 보니 url이 dev 인게 변경이 안 되었네요 =_=
요건 수정하도록 하겠습니다.

2023-04-02 03:36 UTC, 9bow commented on _members/hyekyung-hwang.ko.md
앗, 확인 감사합니다. 빼먹어서 한글글 문서에서도 영문으로 나오고 있었네요;;
아래쪽도 다 수정하겠습니다~

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/9343724/229329850-c92986e1-7e80-4a69-a5b0-653b89ea26e7.png">

2023-04-02 04:22 UTC, level120 approved these changes

2023-04-03 04:52 UTC, justinyoo approved these changes
LGTM 수고하셨습니다!

2023-04-03 04:53 UTC, merged