ADD: README for setting up env & how to use (#1)
cloudbandwagon/cloudbandwagon.github.io pull request #7
Opened 2023-03-26 06:23 UTC by 9bow

홈페이지 사용법 및 개발환경 설정 방법 등을 추가하였습니다.

이해가 안되시는 내용, 빠진 내용 등이 있으면 알려주세요. :)

2023-03-26 07:02 UTC, level120 approved these changes
엄청 친절한 가이드 ㄷㄷ
이제 여기에 i18n이 추가되면 제가 작업했던 것도 마이그레이션해서 올릴께요!

2023-03-26 09:41 UTC, justinyoo requested changes

2023-03-26 09:41 UTC, justinyoo commented on README.md
> +## 클라우드 유랑단 홈페이지
호옥시 헤딩 단계를 맨 처음에 `#`부터 시작하면 어떨까요? 아마도 이 파일은 마크다운 린팅에서 에러를 뱉을 겁니다.

2023-03-26 11:16 UTC, 9bow commented on README.md
> +## 클라우드 유랑단 홈페이지
오, 네네. 상관은 없을거 같은데 ~~전체 문서 기준으로 봤을 때는 repo 제목이 h1 태그일거라~~ 별 일 없으면 문서에서는 h2 부터 시작하고 있기는 하거든요.

덧글 쓰면서 다시 확인해보니까 repo 제목은 h1이 아니고, 아래처럼 접근성을 위해 'sr-only' property가 붙어있는 h1 태그들만 있네요 ㅎㅎ;;

<img width="401" alt="image" src="https://user-images.githubusercontent.com/9343724/227771914-ce50bb69-ae80-4071-aa2d-69d2b877bad0.png">

heading을 한 단계씩 크게 바꿀까요? ~~케케묵은 문서 내에 h1이 하나만 있어야 하는가 하는 주제를 꺼내려는 의도는 아니었습니다 =_=;~~

2023-03-26 12:33 UTC, justinyoo commented on README.md
> +## 클라우드 유랑단 홈페이지
대박, 리포지토리 루트의 HTML 소스를 보니 H1 태그가 10개씩이나... ㅡ,.ㅡ; 그래도 README 문서 자체만 놓고 보면 H1 부터 시작하는 게 맞긴 할 것 같네욥.

2023-03-27 22:40 UTC, justinyoo approved these changes
LGTM!

2023-03-27 23:23 UTC, merged